#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=16,walltime=999:00:00
#PBS -N pick_precursors
#PBS -j oe
#PBS -q default

# Structure of command inputs:
# python phase_picker.py "seismogram directory (full path recommended)" "phase to pick (use exact capitalization!)" "model to pick with (no need to change for now)"
# Example:
# python phase_picker.py /home/username/seismograms/scs/ ScS models/model_name.h5

# Cd into the directory where the script is. Or just add the proper paths to the script and model below
cd Documents/seismology/

python pred_crossecs.py -N 10 -b -400 -e -80 ~/Documents/seismograms/SS_corrected/SS_corrected$PBS_ARRAYID experimental/ss_ind_precursors/ pickerlite/models/SS_40_model.h5
